/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.lista.lutadores;

/**
 *
 * @author manoel
 */
public class Tela extends javax.swing.JFrame {

    private Lutador lutador1 = new Lutador();
    private Lutador lutador2 = new Lutador();

    
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pgrLutador1 = new javax.swing.JProgressBar();
        pgrLutador2 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        btnApanharLutador2 = new javax.swing.JButton();
        btnApanharLutador1 = new javax.swing.JButton();
        btnConcentrarLutador2 = new javax.swing.JButton();
        btnConcentrarLutador1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pgrLutador1.setValue(100);
        pgrLutador1.setPreferredSize(new java.awt.Dimension(150, 15));

        pgrLutador2.setValue(100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/lista/lutadores/ryuvsbison.png"))); // NOI18N

        btnApanharLutador2.setText("Apanhar");
        btnApanharLutador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApanharLutador2ActionPerformed(evt);
            }
        });

        btnApanharLutador1.setText("Apanhar");
        btnApanharLutador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApanharLutador1ActionPerformed(evt);
            }
        });

        btnConcentrarLutador2.setText("Concentrar força");
        btnConcentrarLutador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcentrarLutador2ActionPerformed(evt);
            }
        });

        btnConcentrarLutador1.setText("Concentrar força");
        btnConcentrarLutador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcentrarLutador1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("Ryu");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setText("Bison");

        lblResultado.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblResultado.setText("            ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pgrLutador1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pgrLutador2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnApanharLutador1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnConcentrarLutador1, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnApanharLutador2)
                                    .addComponent(btnConcentrarLutador2))))
                        .addGap(15, 15, 15))))
            .addGroup(layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(lblResultado)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pgrLutador1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(pgrLutador2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(btnApanharLutador2))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConcentrarLutador2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(104, 104, 104)
                        .addComponent(btnApanharLutador1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConcentrarLutador1))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblResultado)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApanharLutador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApanharLutador2ActionPerformed
        if (!lutador1.getPerdeu() && !lutador2.getPerdeu()) {
            lutador2.apanhar();
            atualizarTela();
        }
    }//GEN-LAST:event_btnApanharLutador2ActionPerformed

    private void btnApanharLutador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApanharLutador1ActionPerformed
        if (!lutador1.getPerdeu() && !lutador2.getPerdeu()) {
            lutador1.apanhar();
            atualizarTela();
        }
    }//GEN-LAST:event_btnApanharLutador1ActionPerformed

    private void btnConcentrarLutador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcentrarLutador1ActionPerformed
        if (!lutador1.getPerdeu() && !lutador2.getPerdeu()) {
            lutador1.concentrar();
            atualizarTela();
        }
    }//GEN-LAST:event_btnConcentrarLutador1ActionPerformed

    private void btnConcentrarLutador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcentrarLutador2ActionPerformed
        if (!lutador1.getPerdeu() && !lutador2.getPerdeu()) {
            lutador2.concentrar();
            atualizarTela();
        }
    }//GEN-LAST:event_btnConcentrarLutador2ActionPerformed

    private void atualizarTela() {
        pgrLutador1.setValue(lutador1.getVida());
        pgrLutador2.setValue(lutador2.getVida());
        
        if (lutador1.getPerdeu() || lutador2.getPerdeu()) {
            lblResultado.setText(lutador1.getPerdeu() ? "Lutador 1 perdeu" : "Lutador 2 perdeu");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApanharLutador1;
    private javax.swing.JButton btnApanharLutador2;
    private javax.swing.JButton btnConcentrarLutador1;
    private javax.swing.JButton btnConcentrarLutador2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JProgressBar pgrLutador1;
    private javax.swing.JProgressBar pgrLutador2;
    // End of variables declaration//GEN-END:variables
}
