/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.corredor;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.UIManager;

/**
 *
 * @author manoe
 */
public class Tela extends javax.swing.JFrame {

    Corredor corredor;

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNovoMaratonista = new javax.swing.JButton();
        btnNovoVelocista = new javax.swing.JButton();
        btnNovoTriatleta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblFisico = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPerformance = new javax.swing.JLabel();
        lblTempoMedio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNovoMaratonista.setText("Nasce um maratonista ");
        btnNovoMaratonista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoMaratonistaActionPerformed(evt);
            }
        });

        btnNovoVelocista.setText("Nasce um velocista");
        btnNovoVelocista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoVelocistaActionPerformed(evt);
            }
        });

        btnNovoTriatleta.setText("Nasce um triatleta");
        btnNovoTriatleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoTriatletaActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo físico:");

        lblFisico.setText("---");

        jLabel3.setText("Performance:");

        jLabel4.setText("Tempo médio correndo:");

        lblPerformance.setText("---");

        lblTempoMedio.setText("---");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovoMaratonista)
                    .addComponent(btnNovoVelocista)
                    .addComponent(btnNovoTriatleta)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFisico))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPerformance))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTempoMedio)))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovoMaratonista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNovoVelocista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNovoTriatleta)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblFisico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblPerformance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblTempoMedio))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoMaratonistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoMaratonistaActionPerformed
        corredor = new Maratonista();
        atualizarTela();
    }//GEN-LAST:event_btnNovoMaratonistaActionPerformed

    private void btnNovoVelocistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoVelocistaActionPerformed
        corredor = new Velocista();
        atualizarTela();
    }//GEN-LAST:event_btnNovoVelocistaActionPerformed

    private void btnNovoTriatletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoTriatletaActionPerformed
        corredor = new Triatleta();
        atualizarTela();
    }//GEN-LAST:event_btnNovoTriatletaActionPerformed

    private void atualizarTela() {
        lblFisico.setText(corredor.getTipoFisico());
        lblPerformance.setText(corredor.getPerformance());
        lblTempoMedio.setText(String.format("%.0f segundos", corredor.getTempoMedio()));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovoMaratonista;
    private javax.swing.JButton btnNovoTriatleta;
    private javax.swing.JButton btnNovoVelocista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblFisico;
    private javax.swing.JLabel lblPerformance;
    private javax.swing.JLabel lblTempoMedio;
    // End of variables declaration//GEN-END:variables
}
