/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.lista.elevadors;

/**
 *
 * @author manoel
 */
public class Tela extends javax.swing.JFrame {

    private Elevador elevador1 = new Elevador();
    private Elevador elevador2 = new Elevador();
    
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEntrarHomemElevador1 = new javax.swing.JButton();
        btnEntrarMulherElevador1 = new javax.swing.JButton();
        btnEntrarCriancaElevador1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTotalPassageirosElevador1 = new javax.swing.JLabel();
        lblTotalPesoElevador1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnEntrarCriancaElevador2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTotalPassageirosElevador2 = new javax.swing.JLabel();
        lblTotalPesoElevador2 = new javax.swing.JLabel();
        btnEntrarHomemElevador2 = new javax.swing.JButton();
        btnEntrarMulherElevador2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEntrarHomemElevador1.setText("Entrar Homem");
        btnEntrarHomemElevador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarHomemElevador1ActionPerformed(evt);
            }
        });

        btnEntrarMulherElevador1.setText("Entrar Mulher");
        btnEntrarMulherElevador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarMulherElevador1ActionPerformed(evt);
            }
        });

        btnEntrarCriancaElevador1.setText("Entrar Criança");
        btnEntrarCriancaElevador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarCriancaElevador1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Total de passageiros no elevador:");

        jLabel2.setText("Peso total no elevador:");

        lblTotalPassageirosElevador1.setText("0");

        lblTotalPesoElevador1.setText("0kg");

        btnEntrarCriancaElevador2.setText("Entrar Criança");
        btnEntrarCriancaElevador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarCriancaElevador2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Total de passageiros no elevador:");

        jLabel6.setText("Peso total no elevador:");

        lblTotalPassageirosElevador2.setText("0");

        lblTotalPesoElevador2.setText("0kg");

        btnEntrarHomemElevador2.setText("Entrar Homem");
        btnEntrarHomemElevador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarHomemElevador2ActionPerformed(evt);
            }
        });

        btnEntrarMulherElevador2.setText("Entrar Mulher");
        btnEntrarMulherElevador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarMulherElevador2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEntrarHomemElevador1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEntrarMulherElevador1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEntrarCriancaElevador1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalPassageirosElevador1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalPesoElevador1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEntrarHomemElevador2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEntrarMulherElevador2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEntrarCriancaElevador2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalPassageirosElevador2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotalPesoElevador2)))
                        .addGap(0, 67, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrarHomemElevador1)
                    .addComponent(btnEntrarMulherElevador1)
                    .addComponent(btnEntrarCriancaElevador1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTotalPassageirosElevador1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTotalPesoElevador1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrarHomemElevador2)
                    .addComponent(btnEntrarMulherElevador2)
                    .addComponent(btnEntrarCriancaElevador2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblTotalPassageirosElevador2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblTotalPesoElevador2))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarHomemElevador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarHomemElevador1ActionPerformed
        elevador1.entrarHomem();
        atualizarElevador1();
    }//GEN-LAST:event_btnEntrarHomemElevador1ActionPerformed

    private void btnEntrarMulherElevador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarMulherElevador1ActionPerformed
        elevador1.entrarMulher();
        atualizarElevador1();
    }//GEN-LAST:event_btnEntrarMulherElevador1ActionPerformed

    private void btnEntrarCriancaElevador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarCriancaElevador1ActionPerformed
        elevador1.entrarCrianca();
        atualizarElevador1();
    }//GEN-LAST:event_btnEntrarCriancaElevador1ActionPerformed

    private void btnEntrarHomemElevador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarHomemElevador2ActionPerformed
        elevador2.entrarHomem();
        atualizarElevador2();
    }//GEN-LAST:event_btnEntrarHomemElevador2ActionPerformed

    private void btnEntrarMulherElevador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarMulherElevador2ActionPerformed
        elevador2.entrarMulher();
        atualizarElevador2();
    }//GEN-LAST:event_btnEntrarMulherElevador2ActionPerformed

    private void btnEntrarCriancaElevador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarCriancaElevador2ActionPerformed
        elevador2.entrarCrianca();
        atualizarElevador2();
    }//GEN-LAST:event_btnEntrarCriancaElevador2ActionPerformed

    private void atualizarElevador1() {
        lblTotalPassageirosElevador1.setText(elevador1.getQtdPessoas().toString());
        lblTotalPesoElevador1.setText(elevador1.getPeso().toString() + "kg");
    }
    
    private void atualizarElevador2() {
        lblTotalPassageirosElevador2.setText(elevador2.getQtdPessoas().toString());
        lblTotalPesoElevador2.setText(elevador2.getPeso().toString() + "kg");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrarCriancaElevador1;
    private javax.swing.JButton btnEntrarCriancaElevador2;
    private javax.swing.JButton btnEntrarHomemElevador1;
    private javax.swing.JButton btnEntrarHomemElevador2;
    private javax.swing.JButton btnEntrarMulherElevador1;
    private javax.swing.JButton btnEntrarMulherElevador2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTotalPassageirosElevador1;
    private javax.swing.JLabel lblTotalPassageirosElevador2;
    private javax.swing.JLabel lblTotalPesoElevador1;
    private javax.swing.JLabel lblTotalPesoElevador2;
    // End of variables declaration//GEN-END:variables
}
